#!/usr/bin/env python3
"""Generate the EDID (128-byte base block, EDID 1.3) the LT8619C presents to the HDMI source.

Preferred mode = AT070TN92 typical timing (datasheet 3.3.3):
  800x480, Htotal 1056 (HFP 210, HS 20, HBP 26 -> HS blanking 46), Vtotal 525 (VFP 22, VS 10, VBP 13
  -> VS blanking 23), 60 Hz -> 33.26 MHz pixel clock.  The panel runs in DE mode so only the
  totals and the active area matter.
"""
import sys

PCLK_KHZ = 33260
H = dict(act=800, fp=210, sync=20, bp=26)
V = dict(act=480, fp=22, sync=10, bp=13)
SIZE_MM = (154, 86)


def dtd():
    hbl = H["fp"] + H["sync"] + H["bp"]
    vbl = V["fp"] + V["sync"] + V["bp"]
    pc = PCLK_KHZ // 10
    d = [pc & 0xFF, pc >> 8,
         H["act"] & 0xFF, hbl & 0xFF, ((H["act"] >> 8) << 4) | (hbl >> 8),
         V["act"] & 0xFF, vbl & 0xFF, ((V["act"] >> 8) << 4) | (vbl >> 8),
         H["fp"] & 0xFF, H["sync"] & 0xFF,
         ((V["fp"] & 0xF) << 4) | (V["sync"] & 0xF),
         ((H["fp"] >> 8) << 6) | ((H["sync"] >> 8) << 4) | ((V["fp"] >> 4) << 2) | (V["sync"] >> 4),
         SIZE_MM[0] & 0xFF, SIZE_MM[1] & 0xFF, ((SIZE_MM[0] >> 8) << 4) | (SIZE_MM[1] >> 8),
         0, 0, 0x18]                      # digital separate sync, H-/V-
    return d


def text_desc(tag, s):
    b = s.encode()[:13]
    b = b + (b"\n" if len(b) < 13 else b"") 
    b = b + b" " * (13 - len(b))
    return [0, 0, 0, tag, 0] + list(b)


def edid():
    e = [0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00]
    mfg = ((ord("L") - 64) << 10) | ((ord("C") - 64) << 5) | (ord("D") - 64)
    e += [mfg >> 8, mfg & 0xFF, 0x70, 0x07, 1, 0, 0, 0, 1, 36]   # product 0x0770, week 1, 2026
    e += [1, 3, 0x80, 15, 9, 0x78, 0x0E]                               # EDID1.3, digital, 15x9cm, 2.2, RGB, sRGB
    e += [0xEE, 0x91, 0xA3, 0x54, 0x4C, 0x99, 0x26, 0x0F, 0x50, 0x54]   # sRGB chromaticity
    e += [0x00, 0x00, 0x00]                                              # no established timings (no scaler!)
    e += [0x01, 0x01] * 8                                                # no standard timings
    e += dtd()
    htot = H["act"] + H["fp"] + H["sync"] + H["bp"]
    hk = PCLK_KHZ // htot
    e += [0, 0, 0, 0xFD, 0, 55, 65, hk - 1, hk + 1, 5, 0, 0x0A] + [0x20] * 6   # range limits
    e += text_desc(0xFC, "AT070TN92")
    e += text_desc(0xFF, "LT8619C-800")
    e += [0]                                                             # no extension blocks
    assert len(e) == 127, len(e)
    e.append((-sum(e)) & 0xFF)
    assert sum(e) % 256 == 0
    return e


if __name__ == "__main__":
    e = edid()
    out = sys.argv[1] if len(sys.argv) > 1 else "src/edid.h"
    with open(out, "w") as f:
        f.write("/* generated by tools/make_edid.py - 800x480@60 (33.26 MHz) for the AT070TN92 */\n")
        f.write("#ifndef EDID_H\n#define EDID_H\n#include <stdint.h>\nstatic const uint8_t edid_800x480[128] = {\n")
        for i in range(0, 128, 8):
            f.write("  " + ", ".join("0x%02X" % b for b in e[i:i + 8]) + ",\n")
        f.write("};\n#endif\n")
    open(out.replace(".h", ".bin"), "wb").write(bytes(e))
    print("EDID written to", out)
